apiVersion: v1
kind: Service
metadata:
  name: polling-app-server
  labels:
    app: polling-app-server
spec:
  type: ClusterIP 
  selector:
    app: polling-app-server   # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8080
    targetPort: 8080
     