---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-mysql-service"
spec:
  ports:
    -
        name: "mysql"
        protocol: "TCP"
        port: 3306
        targetPort: 3306 
        nodePort: 0
  selector: {} 
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-mysql-service" 
subsets: 
  -
    addresses:
      -
        ip: "10.0.3.8" 
    ports:
      -
        port: 3306 
        name: "mysql"